### ISSUE TITLE
Allow templates with qute.html extension 

### ISSUE THREAD

**Issue by kucharzyk** [quarkiverse/quarkus-qute-web#70] opened 2024-01-04 22:45 UTC
Currently quarkus-qute-web only supports templates with common extensions like .html

```
/pub/foo.html -> /foo
```

I would like to use qute.html extensions. Such templates are commonly used with qute

```
/pub/foo.qute.html -> /foo
```

Unfortunately currently it's not supported and /pub/foo.qute.html  won't be mapped to /foo
It would be nice to support both to have more consistency between qute and qute-web.

**Comment by kucharzyk** [comment] 2024-01-04 22:48
@mkouba I've opened PR to fix this issue

**Comment by mkouba** [comment] 2024-01-09 07:56
For the record,  the problem is only related to index pages. In other words, `/pub/foo.qute.html` -> `/foo` works just fine but `/pub/index.qute.html` -> `/` does not.

Fixed in https://github.com/quarkiverse/quarkus-qute-web/pull/71.

**Closed by mkouba** 2024-01-09 07:56 UTC
